webstack:
  image: pitchtanks/web
  ports:
    - "80:8080"
  links:
    - db
  command: 'npm start'
  environment:
    PORT: '8080'
  restart: always
db:
  image: mongo
  expose:
    - "27017"
    - "27018"
    - "27019"
    - "28017"
